flekschas/jupyter-scatter

js/src/codecs.js, js/src/index.js, jscatter/jscatter.py, jscatter/widget.py, requirements.txt
Changes `points` and `selection` to use different serde (rather than traitlets `List`). Currently assumes that `points` and `selection` will be 2D numpy arrays.
TODO:
_NOTE_: `regl-scatterplot` requires data to be in a nested/interleaved structure: `[[x0, y0, ...], [x1, y1, ...]]`. I'm not sure how feasible it would be, but we could likely improve the overhead of data-transfer further if we could pass columnar data to `scatterplot.draw()`, e.g.:
```javascript
scatterplot.draw({
x: new Float32Array(...),
y: new Float32Array(...),
category: new Float32Array(...),
value: new Float32Array(...),
});
```
In python, the underlying `points`/`selection` arrays could be column-major order (`order="F"`), which means that we could de-serialize the `memoryview` on the client into individual columnar …
=> Use custom (de)serialization for `points`/`selection`

MANIFEST.in, README.md, install.json, pyproject.toml, setup.cfg, setup.py, test-environment/README.md
**Motivation**:
- JS currently must be manually built (`npm install && npm run build`) for the repo. 
- `jupyter-scatter` does not automatically install extension with `pip install jupyter-scatter`.
Newer versions of Jupyter and JupyterLab support automatic installation of extensions from PyPI (not local dev install with `pip install -e .`). This PR will make jupyter-scatter automatically install extensions with `pip install jupyter-scatter`.
~Blocking:~
~- Mixed naming of `jscatter`/`jupyter-scatter` seems to cause an issue for auto install of jupyter notebook extension.~
**How to try out this PR?**
```bash
pip install build
python -m build . # inside jupyter-scatter dir
pip install dist/jupyter-scatter-0.2.0.tar.gz
jupyter nbextension list
jupyter labextension list
```
**How to actually …
=> Upgrade packaging for automatic install

API.md, CHANGELOG.md, js/src/legend.js, jscatter/encodings.py, jscatter/jscatter.py, jscatter/types.py, jscatter/utils.py, requirements.txt, setup.cfg
This PR adds a new argument called `labeling` to the `color()`, `opacity()`, `size()`, `connection_color()`, `connection_opacity()`, and `connection_size()` methods. This argument allows defining end labels (i.e., labels for the minimum and maximum value) for continuous data encoding. If defined, those labels will be shown in the legend.
For example:
```python
data = np.random.rand(500, 4)
df = pd.DataFrame(data, columns=['mass', 'speed', 'pval', 'group'])
df['group'] = df['group'].map(lambda c: chr(65 + round(c)), na_action=None)
sc = jscatter.Scatter(
data=df,
x='mass',
y='speed',
color_by='mass',
color_map='plasma',
color_order='reverse',
color_norm=[0, 1],
color_labeling=['low', 'high'],
size_by='pval',
size_norm=[0, 1], …
```
=> Add support for legend end labeling

API.md, CHANGELOG.md, js/package-lock.json, js/package.json, js/src/index.js, jscatter/jscatter.py, jscatter/widget.py
This PR integrate's regl-scatterplots new `zoomToPoints()` method via a new `scatter.zoom()` method.
**Example:**
```python
#########
df = pd.DataFrame(np.random.rand(500, 4), columns=['mass', 'speed', 'pval', 'group'])
df['group'] = df['group'].map(lambda c: chr(65 + round(c)), na_action=None)
sc = jscatter.Scatter(data=df, x='mass', y='speed')
sc.selection(df.query('mass > 0.4 and mass < 0.6 and speed > 0.4 and speed < 0.6').index)
sc.show()
#########
sc.zoom(sc.selection())
#########
sc.zoom(None)
```
https://user-images.githubusercontent.com/932103/203417646-2fd0ba60-9192-4aaa-8d08-9cc494328b56.mp4
=> Add support for zooming to points

CHANGELOG.md, js/package.json
Should fix #37
Google Colab and VSCode rely on loading the bundled _extension_ (`dist/index.js`) from a CDN. I believe Colab uses unpkg, but others may use jsdelivr, etc. 
CDNs generally defer to the `main` field of the `package.json` (since this is how Node's resolution algorithm works), but there are unofficial fields like `unpkg`, `jsdelivr`, `module`, `browser`, etc. It would be simple enough to make the `main` field `dist/index.js` to support most CDNs, but then that breaks `jupyterlab extension build` (which requires the `main` to be `src/index.js`). Fix one leak and another opens 🙃 
This PR uses [`publishConfig`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#publishconfig) – an formal field used by `npm` (and other package managers) to override properties in the …
=> fix: correct `main` field in package.json for CDN support

js/webpack.config.js
FWIW, I don't think the `dist/index.js` is consumed anywhere by either Jupyter or JupyterLab. It is just intended for Google Colab or VSCode and doesn't seem to be working. Hopefully this does the fix, but honestly it is so hard to know (and so hard to debug without pushing to NPM).
This PR aligns embed config in the `webpack.config.js` with the latest from the cookiecutter template. It changes the amd output from an named module to an unnamed module.
Suggested here: https://github.com/flekschas/jupyter-scatter/pull/51#issuecomment-1347641482
=> chore: make embed export and unnamed module

API.md, CHANGELOG.md, js/package-lock.json, js/package.json, js/src/index.js, jscatter/jscatter.py, jscatter/widget.py
This PR addresses #61 and adds two new methods for filtering and updating the data: `scatter.filter()` and `scatter.data()`
**API**:
```py
scatter.filter(point_idxs=[0, 1, 2])
```
**Example**:
```py
x = np.random.rand(500)
y = np.random.rand(500)
s1 = jscatter.Scatter(x=x, y=y)
s2 = jscatter.Scatter(x=x, y=y, zoom_on_filter=True)
def on_selection_change(change):
s2.filter(change.new)
s1.widget.observe(on_selection_change, names='selection')
ipywidgets.HBox([s1.show(), s2.show()])
```
https://user-images.githubusercontent.com/932103/223148819-04060f54-9dc1-424c-bb3c-851f04d7690d.mp4
**API**:
```py
scatter.data(data=df)
```
**Example**:
```py
data = np.random.rand(500, 4)
df = pd.DataFrame(data, columns=['mass', 'speed', 'pval', 'group'])
df['group'] = df['group'].map(lambda c: chr(65 + …
```
=> New `scatter.filter()` and `scatter.data()` methods

js/src/codecs.js
I'm not sure but I was running into an issue where `this` was undefined in the codec, throwing an error when syncing selections. I'm not sure where the issue is coming from, but this PR just avoids relying on `this` and instead passes the `dtype` from a closure.
=> fix: avoid ES6 class for codec

CHANGELOG.md, js/package-lock.json, js/package.json, jscatter/encodings.py, jscatter/jscatter.py
This PR makes sure that the legend for categorical encodings respects the order of the dict defining the encoding (if specified)
Previously, the legend would print out the categories in the order they appear in the data, even if you specify a different order via a dictionary. Now the legend settings are ordered according to the dictionary. If you did not specify the encoding via a dictionary, nothing changes.
In the following example, the legend will read `C`, `B`, `D`, `E`, `F`, `A`, `G`, and `H`.
```py
scatter = jscatter.Scatter('x', 'y', df, legend=True)
scatter.color(by='group', map=dict(
C='red',
B='blue',
D='pink',
E='green',
F='brown',
A='yellow',
G='gray',
H='deepskyblue',
))
scatter.show()
```
Sometimes the …
=> feat: respect categorical encoding map order

.github/PULL_REQUEST_TEMPLATE.md, API.md, CHANGELOG.md, js/package-lock.json, js/package.json, js/src/index.js, js/src/utils.js, jscatter/encodings.py, jscatter/jscatter.py, jscatter/types.py, jscatter/utils.py, jscatter/widget.py
This PR adds support for showing a tooltip upon hovering a point.
This PR adds a new method to the `Scatter` class called `tooltip`:
```py
scatter = Scatter(data=df, x='mass', y='speed', color_by='group', size=6, tooltip=True)
scatter.tooltip(true, contents={'color'})
```
https://github.com/flekschas/jupyter-scatter/assets/932103/eeae0635-d12a-46d3-a9b3-cd2515d699b9
https://github.com/flekschas/jupyter-scatter/assets/932103/258d0b93-50e9-4c28-a45f-928d6973a435
It makes it easier to interpret data points by showing the underlying data that is visually encoded by the `x`, `y`, `color`, `opacity`, or `size` channel.
=> feat: tooltip

CHANGELOG.md, js/src/index.js, jscatter/compose.py
This PR fixes two issues with axes of linked scatter plots: it makes sure the x-axes are always shown and that all axes updated appropriately upon view changes.
The missing x-axes was a result of an incorrect assigned height. With this fix the height of the scatter plots shrinks to give space to the x-axes.
With this PR, all axes also update appropriately upon pan & zoom events of linked scatter plots
https://github.com/flekschas/jupyter-scatter/assets/932103/ee6cd826-4d14-4bc7-b611-d5f3259dcc97
Fixes #84
Fixes #87
=> fix: show missing x-axes and updating all axes of linked scatter plots upon pan&zoom

.gitignore, CHANGELOG.md, js/package-lock.json, js/package.json, js/src/index.js, js/src/legend.js, jscatter/encodings.py, jscatter/jscatter.py
This PR fixes several smaller glitches around the updating of the `color`, `opacity`, and `size` domains, the `x`/`y` data updating, and legend formatting.
1. Fix: update `color`, `opacity`, and `size` scales (on the front-end) as the respective domains update
2. Fix: reset `x` and `y` scale domains to the new min/max data values when the `x` and `y` data is updated
3. Fix: use better number formatting for the legend
4. Fix: update `regl-scatterplot` to `v1.8.4` which fixes a bug related to the opacity encoding
1. Previously, when the widget's `color_domain`, `opacity_domain`, or `size_domain` would upadate, the front-end would not automatically update the corresponding scale functions and the tooltip would show outdated …
=> fix: several smaller issues

CHANGELOG.md, js/src/index.js, jscatter/compose.py
This PR fixes three bugs:
1. make sure view synchronization works when `axes=False`
2. properly adjust scatter height when `compose()`ing scatters that have titles, axes labels, or no axes
3. make sure the tooltip doesn't use a stale channel value getter function
View sync and height adjustment works as expected:
https://github.com/flekschas/jupyter-scatter/assets/932103/c6e35059-0002-430e-befe-dc4c17f4c6c1
Tooltip getter is fresh as expected:
https://github.com/flekschas/jupyter-scatter/assets/932103/ebbeb661-69f9-4052-b875-07ee8e600b69
Previously,
1. view synching wouldn't due to regression from #88 (https://github.com/flekschas/jupyter-scatter/pull/88/files#diff-3aa09978cb18aff029d3dd6535a2b9ee0a8c4df561ceae68517deb6bac6ffa …
=> fix: view synchronization without axes, propper compose heights, tooltip value getters

CHANGELOG.md, jscatter/jscatter.py
This PR fixes a long-standing issue when mixing DataFrame-based and custom data.
Previously, `color_by`, `opacity_by`, `size_by`, `connect_by`, `connect_order`, `connection_color_by`, `connection_opacity_by`, and `connection_size_by` only worked with a bound DataFrame.
With this fix, one can mix referencing data from a bound DataFrame or passing in custom data. E.g.:
```py
scatter = jscatter.Scatter(
data=pd.DataFrame({
"x": [1, 2, 3],
"y": [8, 3, 0],
"color": ["0", "0", "1"],
"opacity": [1, 1, 0],
}),
x="x",
y="y",
color_by="color",
opacity_by=[1, 1, 0],
opacity_map=(.25, 1, 2),
size=10,
)
scatter.show()
```
Fixes #89
=> fix: allow mixing custom and DataFrame-based data

CHANGELOG.md, README.md, js/src/index.js, js/src/utils.js, jscatter/jscatter.py, jscatter/widget.py, pyproject.toml
This PR addresses two bugs around axis rendering, another bug regarding `options`, and improves the tooltip positioning.
1. When initializing a `Scatter` instance, the `options` are properly used by `regl-scatterplot` (previously `options` were only applied after the initialization of a `Scatter` instance) (#106)
2. The x/y axis now use the appropriate x/y scale domain instead of the x/y data domain. (#107)
3. Upon resizing the browser window, the x/y axes are now properly rerendered. (#108)
4. The tooltip position incorporates the most up to date bounding box and offset to avoid cutting the tooltip off
Fixes #106
Fixes #107
Fixes #108
Improves the tooltip positioning
> Testing
I used the following example for testing
```py …
```
=> fix: address several issues regarding the axis rendering

jscatter/widget.py
Removes `JupyterScatter.hovering_widget`. The `JupyterScatter.hovered_point`
property is not defined anywhere on the widget. I believe this traitlet was
likely added at some time but was removed, and this bug hasn't popped up due to
lack of accessing this field from others.
A recent release of `anywidget` inspects the fields on the widget class within
`__init__`, which invokes the `@property` decorator on the `hovering_widget`.
This led to an attribute error.
Fixes #115
=> fix: Remove JupyterScatter.hovering_widget

CHANGELOG.md, docs/.vitepress/config.ts, js/src/index.js
Fixes a common typo of Tooltip (Toolip), which is for example in the docs.
=> fix: tooltip typos

CHANGELOG.md, js/package-lock.json, js/package.json, js/src/index.js, jscatter/jscatter.py, jscatter/utils.py, jscatter/widget.py, pyproject.toml, tests/test_jscatter.py
Reset scale and norm ranges upon updating the associated dataframe.
Upon updating the referenced dataframe, all scale and norm ranges are reset such that they get re-computed with the new data.
E.g., first run
```py
data1 = pd.DataFrame({
"x": np.random.rand(1000),
"y": np.random.rand(1000),
})
data2 = pd.DataFrame({
"x": 2*np.random.rand(1000),
"y": 2*np.random.rand(1000),
})
scatter = jscatter.Scatter(data=data1, x="x", y="y", width=500, height=500)
scatter.show()
```
Then
```py
scatter.data(data2)
```
https://github.com/flekschas/jupyter-scatter/assets/932103/f8878787-aa17-46d4-8607-ad625cc86024
Fixes #131
=> fix: reset scale & norm ranges in `scatter.data()`

CHANGELOG.md, jscatter/jscatter.py, tests/test_jscatter.py
This PR fixes an issue in setting custom axes labels.
This PR ensures that custom axes labels are returned properly.
Fixes #137
=> fix: `scatter.axes(labels=['x_label', 'y_label'])`

CHANGELOG.md, docs/api.md, js/src/index.js, jscatter/jscatter.py, jscatter/widget.py, paper/examples.ipynb
I added a function for programmatically showing the tooltip via `scatter.show_tooltip()`
Added `scatter.show_tooltip(point_index)`. Note that this function only shows a tooltip if the tooltip was activated via `scatter.tooltip(True)`.
Programmatically showing the tooltip can help guide the user to locate a specific point.
=> feat: add `scatter.show_tooltip()`

.github/workflows/build.yml, .github/workflows/ci.yml, CHANGELOG.md, js/package-lock.json, js/package.json
There was an issue with rendering more than 1M points with regl-scatterplot due to a bug introduced in v1.9.0.
Bumped regl-scatterplot from v1.9.8 to v1.10.2
The new version of regl-scatterplot contains a critical bug fix for rendering more than 1M points. For details see https://github.com/flekschas/regl-scatterplot/pull/190
=> fix: bump regl-scatterplot to v1.10.2

CHANGELOG.md, js/package-lock.json, js/package.json
This PR fixed the rendering issue in VSCode
I've updated regl-scatterplot to v1.10.4 which contains the actual fix for the issue. See https://github.com/flekschas/regl-scatterplot/blob/master/CHANGELOG.md#1104 for details.
Fixes #37
> Demo
https://github.com/user-attachments/assets/43500f2f-effb-4ca7-9a2b-02930f3dd61b
=> fix: VSCode rendering bug

README.md
This PR improves the `README` in response to https://github.com/openjournals/joss-reviews/issues/7059#issuecomment-2263459949.
1. I added a more prominent link to https://jupyter-scatter.dev after `**How?**` and before `**Index**` to make it easier to find the documentation.
2. I updated the index to only include anchor links to that point to sections within the `README` (instead of having a mix of anchor and external links)
3. I added a note to the _Install_ and _Development_ sections regarding the need for `Node` when building Jupyter Scatter from source or developing JScatter.
4. I added a note to the _Development_ section on how to run the tests.
To address the issues …
=> docs: update `README` to better point to 

notebooks/linking.ipynb
This PR adds `pyarrow` as a dependency to `linking.ipynb` as identified by https://github.com/openjournals/joss-reviews/issues/7059#issuecomment-2263459949
This PR adds missing `pip install pyarrow` statement to the `linking.ipynb`.
pyarrow is used for an example in the notebook so we should add it as a dependency
=> fix: add missing `pyarrow` dependency

CHANGELOG.md, docs/.vitepress/config.ts, docs/annotations.md, docs/api.md, docs/public/images/annotations-simple-dark.png, docs/public/images/annotations-simple-light.png, docs/public/images/annotations-styles-dark.png, docs/public/images/annotations-styles-light.png, js/src/codecs.js, js/src/index.js, js/src/utils.js, jscatter/__init__.py, jscatter/annotations.py, jscatter/annotations_traits.py, jscatter/jscatter.py, jscatter/widget.py, notebooks/annotations.ipynb, tests/test_annotations.py
This PR adds support for line-based annotations.
This PR adds a new method `scatter.annotations()` to enable drawing annotations. Four types of line-based annotations are supported: horizontal lines (`HLine`), vertical lines (`Vline`), free-form lines (`Line`), and rectangles (`Rect`).
Examples
```py
x1, y1 = np.random.normal(-1, 0.2, 1000), np.random.normal(+1, 0.05, 1000)
x2, y2 = np.random.normal(+1, 0.2, 1000), np.random.normal(+1, 0.05, 1000)
x3, y3 = np.random.normal(+1, 0.2, 1000), np.random.normal(-1, 0.05, 1000)
x4, y4 = np.random.normal(-1, 0.2, 1000), np.random.normal(-1, 0.05, 1000)
y0 = jscatter.HLine(0)
x0 = jscatter.VLine(0)
c1 = jscatter.Rect(x_start=-1.5, x_end=-0.5, y_start=+0.75, y_end=+1.25)
c2 …
```
=> feat: add support for line-based annotations

jscatter/jscatter.py, jscatter/utils.py
This PR fixes several warnings thrown in pytest.
☝️ 
The warning are just annoying to look at :)
=> test: fix pandas deprecation warning and remove unused `tooltip_histograms_bins` argument

CHANGELOG.md, js/src/index.js, jscatter/jscatter.py, pyproject.toml, tests/test_jscatter.py
This PR fixes several smaller glitches
- Upon resizing, the axes grid lines were not rerendered correctly (they should remain dashed)
- When changing the `color_by` and `color_map` property at the same time, we need to take care of a special edge case. When `color_by` is undefined and a color map is set, regl-scatterplot uses the special `pointColorActive` instead of the color map colors. Hence in this case we have to reapply the point color after setting `color_by`.
- Revert the switch from `pd.api.types.is_string_dtype` to `pd.StringDtype.is_dtype` as `pd.StringDtype.is_dtype` is not equivalent to `pd.api.types.is_string_dtype`. Some Pandas APIs are a mess... 😞  (I added tests to verify the behavior now)
- Do not set tooltip title if element is …
=> fix: regressions and smaller visual glitches

CHANGELOG.md, docs/api.md, js/src/index.js, jscatter/jscatter.py, jscatter/widget.py, tests/test_jscatter.py
This PR fixes a regression from #132 which accidentally disabled point transitions when the x or y channels were changed.
The animated point transition is based on a widget property called `transition_points`, which was introduced to make the animation behavior clearer when the data source was changed via `scatter.data()` in #132. Unfortunately, I accidentally forgot to set this property to true when `scatter.x()`, `scatter.y()`, or `scatter.xy()` was used. I've fixed the issue.
Additionally, to offer more control over when points are transitioned and the transition speed, I've added two options to the `Scatter` class that can either be set during initialization or via `scatter.options()`:
- `transition_points`: is a Boolean value to enable or …
=> fix: re-enable point transition and make it explicit

CHANGELOG.md, js/src/index.js
This PR fixes an issue when synchronizing two scatters with different domains
Use internal x/y domains for updating axes for external view synchronizing
Fixes #158 
> Demo
```py
data1 = pd.DataFrame({
"x": np.random.rand(1000),
"y": np.random.rand(1000),
})
data2 = pd.DataFrame({
"x": 200*np.random.rand(1000),
"y": 200*np.random.rand(1000),
})
s0 = jscatter.Scatter(data=data1, x="x", y="y", height=500)
s1 = jscatter.Scatter(data=data2, x="x", y="y", height=500)
jscatter.compose(
[s0, s1],
sync_view = True
)
```
https://github.com/user-attachments/assets/3632aeb5-2524-4721-acc7-d68dbbd120b4
=> fix: use internal x/y domains for updating axes

CHANGELOG.md, docs/api.md, jscatter/jscatter.py
This PR renames the `reset_view` argument of the `scatter.data()` method to `zoom_view` for clarity. The name `reset_view` and method's docstring suggested that the argument updated the origin, which is not the case. By setting `zoom_view` to `True`, all that's happening is that the view is zoomed to the data extent. Whether or not the origin is updated depends on the `reset_scales` argument.
- Refactor: rename the `reset_view` argument of `scatter.data()` to `zoom_view` for clarity
- Docs: add API docs for `reset_scales`, `zoom_view`, and `animate` of `scatter.data()`
Fixes #160
=> refactor: rename `reset_view` to `zoom_view`

CHANGELOG.md, jscatter/utils.py, notebooks/Untitled4.ipynb, tests/test_jscatter.py
This PR reverts back the method for detecting whether a column is of type string.
I reverted back to `pd.api.types.is_string_dtype` from `pd.StringDType` because the two function, albeit looking semantically identical, do not do the same thing. The former detects object and string types while the latter only strictly detects string types. This is confusing as `pd.Series(['a', 'b'])` is of type `object`. So:
```py
pd.StringDtype.is_dtype(pd.Series(['a', 'b'])) == False
pd.api.types.is_string_dtype(pd.Series(['a', 'b'])) == True
```
[Wat?!](https://www.destroyallsoftware.com/talks/wat)
Fixes #166 
> Test Case
```py
data = pd.DataFrame({
"x": np.random.rand(1000),
"y": …
```
=> fix: revert to `pd.api.types.is_string_dtype`

CHANGELOG.md, docs/api.md, js/package-lock.json, js/package.json, js/src/index.js, jscatter/jscatter.py, jscatter/types.py, jscatter/widget.py, tests/test_jscatter.py
This PR introduces a new property called `size_scale_function` to allow customizing the point size's zoom scale function.
This PR exposes regl-scatterplot's `pointScaleMode` (added by @abast! Thanks again 🎉 ) via `scatter.size(scale_function)`. You can choose between
- `asinh` (default)
- `linear`
- `constant` (a.k.a., no zoom-based scaling)
Because it's a neat feature to have and it's already implemented in regl-scatterplot
> Demo
Zoom-based scale functions in the following order:
1. `asinh`
2. `linear`
3. `constant`
https://github.com/user-attachments/assets/7e373c87-7f3a-4a7c-ace4-1244fdc3c13b
=> feat: allow customizing the point size's zoom scale function

CHANGELOG.md, docs/api.md, docs/link-multiple-plots.md, js/package-lock.json, js/package.json, js/src/index.js, jscatter/jscatter.py, jscatter/widget.py, tests/test_jscatter.py
This PR adds support for disabling pan/zoom via `scatter.camera(is_fixed=True)`
You can control the camera's fixed state via
- `Scatter(camera_is_fixed=True)`
- `scatter.camera(is_fixed=True)`
Note that when the camera is fixed, manual pan and zoom is disabled. However, you can still pan and zoom programmatically via `scatter.zoom()`
Fixes #176
> Demo
https://github.com/user-attachments/assets/ac850945-82ec-487d-a4ba-97a922565627
=> fix: allow disabling pan/zoom by fixing the camera

CHANGELOG.md, docs/api.md, docs/interactions.md, docs/package-lock.json, docs/package.json, docs/public/videos/interactions-lasso-add-remove-dark.mp4, docs/public/videos/interactions-lasso-add-remove-light.mp4, docs/public/videos/interactions-lasso-brush-dark.mp4, docs/public/videos/interactions-lasso-brush-light.mp4, docs/public/videos/interactions-lasso-rectangle-dark.mp4, docs/public/videos/interactions-lasso-rectangle-light.mp4, js/package-lock.json, js/package.json, js/src/codecs.js, js/src/histogram.js, js/src/index.js, jscatter/jscatter.py, jscatter/utils.py, jscatter/widget.py, jscatter/widgets/__init__.py, jscatter/widgets/button.py, jscatter/widgets/button_choice.py, jscatter/widgets/button_slider.py, jscatter/widgets/divider.py, notebooks/Untitled5.ipynb
This PR adds support for rectangle and brush selections and fixes a couple of other issues.
1. Add support for brush and rectangle lasso types. You can activate a different lasso type via the new lasso type button or via `scatter.widget.lasso_type`
2. Expose lasso selection polygon via `scatter.widget.lasso_polygon_selection`.
3. Enable merging of lasso selection upon holding down the [meta key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey) and deselected points upon holding down the [alt key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/altKey).
4. Allow specifying which properties should feature a histogram via `scatter.tooltip(histograms=['color', 'property_a'])`
5. Fix a background histogram render bug
6. Ensure NAs are skipped for the …
=> feat: brush rectangle lasso

jscatter/composite_annotations.py, jscatter/dependencies.py, jscatter/label_placement/label_placement.py, jscatter/label_placement/largest_cluster.py, jscatter/label_placement/resolve_zoom_in_collisions.py, tests/test_dependencies.py
Whenever an import fail, we silently define a mock object. Whenever this object is dereferenced and used, an exception indicating the missing extra is raised.
> Explain in more detail what has changed on a technical level
> If feasable, add a screenshot or video demonstrating the new feature or bug fix
Fixes #___
=> Add robustness to importing extra dependencies
